# -*- coding: utf-8 -*-
"""Copy of Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkmQb8RYM5gEnedq-zvWV2OIO5qHoEF3

# **Installing Dependencies**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb


from sklearn.metrics import classification_report, roc_auc_score, roc_curve, auc, confusion_matrix, RocCurveDisplay


sns.set_style('whitegrid')

"""# **Loading Dataset**"""

df=pd.read_csv('credit_risk_dataset.csv')

"""# **Performing EDA**

"""

df.head()

df.info()

df.shape

df.describe()

df.shape

df.columns

df.isnull().sum()

#We are getting missing values in two columns
#person_emp_length	895
#loan_int_rate	3116

df.isnull().mean()*100
#To check should we drop or fill these

df['person_emp_length'] = df['person_emp_length'].fillna(df['person_emp_length'].median())

df['loan_int_rate'] = df['loan_int_rate'].fillna(df['loan_int_rate'].median())

df.isnull().sum()

df.drop_duplicates(inplace=True)

"""# **Checking** Target Distribution"""

df['loan_status'].value_counts()
df['loan_status'].value_counts(normalize=True)

X = df.drop("loan_status", axis=1)
y = df["loan_status"]

X = pd.get_dummies(X, drop_first=True)

X.head()

"""EDA: Target Distribution"""

sns.countplot(x='loan_status', data=df)
plt.title("Loan Status Distribution")
plt.show()

"""Numerical Feature Distribution"""

num_cols = ['person_age','person_income','person_emp_length','loan_amnt',
            'loan_int_rate','loan_percent_income','cb_person_cred_hist_length']
df[num_cols].hist(bins=20, figsize=(15,10))
plt.suptitle("Numerical Features Distribution")
plt.show()

"""Categorical Features Countplots"""

cat_cols = ['person_home_ownership','loan_intent','loan_grade','cb_person_default_on_file']

for col in cat_cols:
    plt.figure(figsize=(10,5))
    sns.countplot(x=col, data=df, order=df[col].value_counts().index)
    plt.title(f"{col} Distribution")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""Correlation Analysis"""

plt.figure(figsize=(10,6))
sns.heatmap(df[num_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Feature Correlation (Numeric Only)")
plt.show()

"""Feature vs Target"""

plt.figure(figsize=(8,6))
sns.boxplot(x='loan_status', y='loan_amnt', data=df)
plt.title("Loan Amount vs Loan Status")
plt.show()

plt.figure(figsize=(8,6))
sns.countplot(x='person_home_ownership', hue='loan_status', data=df)
plt.title("Home Ownership vs Loan Status")
plt.show()

df.isna().sum()

"""Preprocessing

"""

# Encode categorical features
for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col])

# Features & target
X = df.drop('loan_status', axis=1)
y = df['loan_status']

# Train/test split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_val[num_cols] = scaler.transform(X_val[num_cols])

"""Using XG boost as model"""

# Initialize and train model
xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    random_state=42,
    eval_metric='logloss'
)
xgb_model.fit(X_train, y_train)

# Predictions
y_pred_xgb = xgb_model.predict(X_val)
y_score = xgb_model.predict_proba(X_val)[:,1]

# Performance metrics
print("XGBoost Performance:")
print(classification_report(y_val, y_pred_xgb))
roc_auc_xgb = roc_auc_score(y_val, y_score)
print(f"ROC AUC Score: {roc_auc_xgb:.4f}")

# Feature importance (top 10)
feat_imp = pd.Series(xgb_model.feature_importances_, index=X.columns).sort_values(ascending=False)
plt.figure(figsize=(10,6))
sns.barplot(x=feat_imp[:10], y=feat_imp.index[:10])
plt.title("Top 10 Feature Importances - XGBoost")
plt.show()

# ROC Curve
fpr, tpr, thresholds = roc_curve(y_val, y_score)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - XGBoost')
plt.legend(loc="lower right")
plt.show()

best_model = xgb_model
y_best = y_pred_xgb

cm = confusion_matrix(y_val, y_best)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix - XGBoost")
plt.show()

































